from __future__ import annotations

import subprocess
from pathlib import Path

# Where, relative to flutter_app/test/, the golden test + its PNG are written.
_TEST_FILE = "visual_golden_test.dart"
_GOLDEN_REL = "visual_golden/actual.png"

# The rect-dump test file (under test/). Its JSON output path is relative to
# the package root, since that is `flutter test`'s working directory.
_RECTS_TEST_FILE = "visual_rects_test.dart"
_RECTS_REL = "test/visual_rects/rects.json"

# NOTE: without loaded fonts, `flutter test` renders text with a placeholder
# box font, so text appears as filled rectangles. Passing `fonts` loads the
# design's real font (via rootBundle) so glyphs render and text metrics match.
_TEMPLATE = """\
// GENERATED by agent/screenshot.py for --visual-validate. Do not edit.
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_app/{screen_file}';

void main() {{
  testWidgets('visual golden', (WidgetTester tester) async {{
    tester.view.physicalSize = const Size({width}, {height});
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
{font_loading}
    await tester.pumpWidget(const MaterialApp(home: {screen_class}()));
    await tester.pumpAndSettle();

    // Network images can't load under flutter_test (all HTTP returns 400),
    // so drain those exceptions; the rest of the screen still captures.
    while (tester.takeException() != null) {{}}

    await expectLater(
      find.byType({screen_class}),
      matchesGoldenFile('{golden_rel}'),
    );
  }});
}}
"""


def build_golden_test(
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
    golden_rel: str = _GOLDEN_REL,
    fonts: list[tuple[str, str]] | None = None,
) -> str:
    """Return the Dart source for a golden test that renders the screen.

    Pure: produces the test file contents only. Running it (with
    --update-goldens) is what writes the PNG. `fonts` is a list of
    (family, asset-path) loaded before rendering so glyphs are real.
    """
    return _TEMPLATE.format(
        screen_class=screen_class,
        width=width,
        height=height,
        screen_file=screen_file,
        golden_rel=golden_rel,
        font_loading=_font_loading_block(fonts),
    )


# Dumps every keyed widget's rect (global offset + size) to JSON, keyed by the
# Figma node id carried in its ValueKey. First occurrence of an id wins, so a
# deduped component reused at several sites does not produce ambiguous entries.
_RECTS_TEMPLATE = """\
// GENERATED by agent/screenshot.py for --geometry-validate. Do not edit.
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_app/{screen_file}';

void main() {{
  testWidgets('rect dump', (WidgetTester tester) async {{
    tester.view.physicalSize = const Size({width}, {height});
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
{font_loading}
    await tester.pumpWidget(const MaterialApp(home: {screen_class}()));
    await tester.pumpAndSettle();
    while (tester.takeException() != null) {{}}

    final dump = <String, List<double>>{{}};
    for (final element in find.byType(KeyedSubtree).evaluate()) {{
      final key = element.widget.key;
      if (key is! ValueKey || key.value is! String) continue;
      final box = element.renderObject;
      if (box is! RenderBox || !box.hasSize) continue;
      final origin = box.localToGlobal(Offset.zero);
      dump.putIfAbsent(key.value as String, () => <double>[
        origin.dx, origin.dy, box.size.width, box.size.height,
      ]);
    }}
    final file = File('{rects_rel}');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(jsonEncode(dump));
  }});
}}
"""


def _font_loading_block(fonts: list[tuple[str, str]] | None) -> str:
    """Dart that registers each (family, asset path) before the screen pumps.

    Without real fonts, `flutter test` renders text with a placeholder box font
    and text-node sizes are meaningless; loading the design's font makes the
    measured text rects reflect real glyph metrics.
    """
    if not fonts:
        return ""
    # Fonts must load via rootBundle (the test binding services it); awaiting
    # dart:io File reads inside testWidgets hangs under its fake-async zone.
    lines = ["", "    // Load real fonts so text metrics match the design."]
    for family, asset in fonts:
        lines.append(
            f"    await (FontLoader('{family}')"
            f"..addFont(rootBundle.load('{asset}'))).load();"
        )
    return "\n".join(lines)


def build_rect_dump_test(
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
    rects_rel: str = _RECTS_REL,
    fonts: list[tuple[str, str]] | None = None,
) -> str:
    """Return Dart source for a test that dumps every keyed widget's rect.

    Pure: produces the test file contents only. The screen must be generated
    with keying on (codegen.generate(plan, keyed=True)) so each node is wrapped
    in a KeyedSubtree carrying its Figma node id. `fonts` is a list of
    (family, asset-path) loaded before rendering so text rects are real.
    """
    return _RECTS_TEMPLATE.format(
        screen_class=screen_class,
        width=width,
        height=height,
        screen_file=screen_file,
        rects_rel=rects_rel,
        font_loading=_font_loading_block(fonts),
    )


def discover_fonts(flutter_root: str | Path) -> list[tuple[str, str]]:
    """Return [(family, asset path)] for every .ttf/.otf under <root>/fonts/.

    The family is the file stem (so a bundled `fonts/Inter.ttf` registers the
    `Inter` family the codegen emits). Paths are relative to the package root,
    which is `flutter test`'s working directory.
    """
    fonts_dir = Path(flutter_root) / "fonts"
    out: list[tuple[str, str]] = []
    if not fonts_dir.is_dir():
        return out
    for path in sorted(fonts_dir.iterdir()):
        if path.suffix.lower() in (".ttf", ".otf"):
            out.append((path.stem, f"fonts/{path.name}"))
    return out


def capture_rects(
    flutter_root: str | Path,
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
    fonts: list[tuple[str, str]] | None = None,
) -> Path:
    """Render the keyed screen and return the path to the rect-dump JSON.

    Writes the rect-dump test into <flutter_root>/test/, runs it, and returns
    the path to the JSON it produced. Raises RuntimeError if the run fails or
    the JSON is not produced. `fonts` defaults to whatever is under <root>/fonts/.
    """
    root = Path(flutter_root)
    if fonts is None:
        fonts = discover_fonts(root)
    test_dir = root / "test"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_path = test_dir / _RECTS_TEST_FILE
    test_path.write_text(
        build_rect_dump_test(screen_class, width, height, screen_file, fonts=fonts)
    )

    result = subprocess.run(
        ["flutter", "test", f"test/{_RECTS_TEST_FILE}"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    json_path = root / _RECTS_REL
    if result.returncode != 0 or not json_path.exists():
        log = (result.stdout + result.stderr).strip()
        raise RuntimeError(f"flutter rect capture failed:\n{log}")
    return json_path


def capture(
    flutter_root: str | Path,
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
    fonts: list[tuple[str, str]] | None = None,
) -> Path:
    """Render the screen to a PNG via `flutter test --update-goldens`.

    Writes the golden test into <flutter_root>/test/, runs it, and returns
    the path to the produced PNG. Raises RuntimeError if the test run fails
    or the PNG is not produced. `fonts` defaults to whatever is under
    <root>/fonts/ so text renders with real glyphs instead of boxes.
    """
    root = Path(flutter_root)
    if fonts is None:
        fonts = discover_fonts(root)
    test_dir = root / "test"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_path = test_dir / _TEST_FILE
    test_path.write_text(
        build_golden_test(screen_class, width, height, screen_file, fonts=fonts)
    )

    result = subprocess.run(
        ["flutter", "test", "--update-goldens", f"test/{_TEST_FILE}"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    png_path = test_dir / _GOLDEN_REL
    if result.returncode != 0 or not png_path.exists():
        log = (result.stdout + result.stderr).strip()
        raise RuntimeError(f"flutter golden capture failed:\n{log}")
    return png_path
