from __future__ import annotations

import subprocess
from pathlib import Path

# Where, relative to flutter_app/test/, the golden test + its PNG are written.
_TEST_FILE = "visual_golden_test.dart"
_GOLDEN_REL = "visual_golden/actual.png"

# NOTE: `flutter test` renders text with a placeholder test font (real glyphs
# are not loaded), so text appears as filled boxes in the screenshot. The diff
# is therefore most reliable for layout, spacing, color and alignment, and
# only approximate over text-heavy regions.
_TEMPLATE = """\
// GENERATED by agent/screenshot.py for --visual-validate. Do not edit.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_app/{screen_file}';

void main() {{
  testWidgets('visual golden', (WidgetTester tester) async {{
    tester.view.physicalSize = const Size({width}, {height});
    tester.view.devicePixelRatio = 1.0;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);

    await tester.pumpWidget(const MaterialApp(home: {screen_class}()));
    await tester.pumpAndSettle();

    // Network images can't load under flutter_test (all HTTP returns 400),
    // so drain those exceptions; the rest of the screen still captures.
    while (tester.takeException() != null) {{}}

    await expectLater(
      find.byType({screen_class}),
      matchesGoldenFile('{golden_rel}'),
    );
  }});
}}
"""


def build_golden_test(
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
    golden_rel: str = _GOLDEN_REL,
) -> str:
    """Return the Dart source for a golden test that renders the screen.

    Pure: produces the test file contents only. Running it (with
    --update-goldens) is what writes the PNG. Kept separate so it can be
    unit-tested without invoking flutter.
    """
    return _TEMPLATE.format(
        screen_class=screen_class,
        width=width,
        height=height,
        screen_file=screen_file,
        golden_rel=golden_rel,
    )


def capture(
    flutter_root: str | Path,
    screen_class: str,
    width: int,
    height: int,
    screen_file: str = "generated_screen.dart",
) -> Path:
    """Render the screen to a PNG via `flutter test --update-goldens`.

    Writes the golden test into <flutter_root>/test/, runs it, and returns
    the path to the produced PNG. Raises RuntimeError if the test run fails
    or the PNG is not produced.
    """
    root = Path(flutter_root)
    test_dir = root / "test"
    test_dir.mkdir(parents=True, exist_ok=True)
    test_path = test_dir / _TEST_FILE
    test_path.write_text(build_golden_test(screen_class, width, height, screen_file))

    result = subprocess.run(
        ["flutter", "test", "--update-goldens", f"test/{_TEST_FILE}"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    png_path = test_dir / _GOLDEN_REL
    if result.returncode != 0 or not png_path.exists():
        log = (result.stdout + result.stderr).strip()
        raise RuntimeError(f"flutter golden capture failed:\n{log}")
    return png_path
